"""Changed the column name for the id for each column of the asset_inventory table

Revision ID: 093eb5a342c0
Revises: 
Create Date: 2024-11-07 23:52:34.623711
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '093eb5a342c0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraints before renaming
    op.drop_constraint('asset_category_id_fkey', 'asset', type_='foreignkey')
    op.drop_constraint('request_user_id_fkey', 'request', type_='foreignkey')
    op.drop_constraint('request_asset_id_fkey', 'request', type_='foreignkey')

    # Rename the ID column in the asset table
    op.alter_column('asset', 'asset_id', new_column_name='id')

    # Rename the ID column in the request table
    op.alter_column('request', 'request_id', new_column_name='id')

    # Rename the ID column in the user table
    op.alter_column('user', 'user_id', new_column_name='id')

    # Rename the ID column in the category table
    op.alter_column('category', 'category_id', new_column_name='id')

    # Recreate foreign key constraints with updated references
    op.create_foreign_key('asset_category_id_fkey', 'asset', 'category', ['category_id'], ['id'])
    op.create_foreign_key('request_user_id_fkey', 'request', 'user', ['user_id'], ['id'])
    op.create_foreign_key('request_asset_id_fkey', 'request', 'asset', ['asset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraints before renaming back
    op.drop_constraint('asset_category_id_fkey', 'asset', type_='foreignkey')
    op.drop_constraint('request_user_id_fkey', 'request', type_='foreignkey')
    op.drop_constraint('request_asset_id_fkey', 'request', type_='foreignkey')

    # Rename the ID columns back to original names
    op.alter_column('asset', 'id', new_column_name='asset_id')
    op.alter_column('request', 'id', new_column_name='request_id')
    op.alter_column('user', 'id', new_column_name='user_id')
    op.alter_column('category', 'id', new_column_name='category_id')

    # Recreate foreign key constraints with original references
    op.create_foreign_key('asset_category_id_fkey', 'asset', 'category', ['category_id'], ['category_id'])
    op.create_foreign_key('request_user_id_fkey', 'request', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('request_asset_id_fkey', 'request', 'asset', ['asset_id'], ['asset_id'])

    # ### end Alembic commands ###