"""Rename image_url to image_path in user table and in asset table

Revision ID: 184230f95062
Revises: 63febd2c6288
Create Date: 2024-11-08 22:09:33.429054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184230f95062'
down_revision = '63febd2c6288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_path')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
