"""Add image_url to User model

Revision ID: 63febd2c6288
Revises: fc0e4a68d050
Create Date: 2024-11-08 21:40:29.797426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63febd2c6288'
down_revision = 'fc0e4a68d050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
