"""Updated relationships in User and Request models

Revision ID: 9d564e96b176
Revises: 093eb5a342c0
Create Date: 2024-11-08 01:23:41.509493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d564e96b176'
down_revision = '093eb5a342c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        # Add the column as nullable first
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
    
    # Update existing rows to set a default value for the new column
    op.execute('UPDATE request_history SET id = 0')  # Set a default value

    # Alter the column to be NOT NULL
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.alter_column('id', nullable=False)

        # Drop the old column
        batch_op.drop_column('history_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        # Re-add the old column
        batch_op.add_column(sa.Column('history_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###